services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: hack_template
      POSTGRES_PASSWORD: "OVWpzkh8KpbA4k_u8iyW_kQHFrSPZV8Z"
    volumes:
      - hack_template_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "NIYHLqXQMHtqRYgIp0CUm8wNf-XmX6uQ"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: hack_template_test
      POSTGRES_PASSWORD: "eBtVS1l04WI5D_OS8X-9nTvg2LLbuhb6"
    volumes:
      - hack_template_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "DdybgTBFf0Pak9rs2K4COv-hj_pgC2pT"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  hack_template_data:
  hack_template_test_data:
