name: hack_template_flutter
description: A new Flutter project with Serverpod.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
    
  serverpod_flutter: 2.9.1
  hack_template_client:
    path: ../hack_template_client

  cupertino_icons: ^1.0.5
  injectable: ^2.5.1
  get_it: ^8.2.0
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  meta: ^1.16.0
  freezed_annotation: ^3.1.0
  go_router: ^16.2.1
  talker_flutter: ^5.0.0
  talker_bloc_logger: ^5.0.0

dev_dependencies:
  build_runner: ^2.7.1
  build_verify: ^3.1.1
  flutter_lints: '>=3.0.0 <7.0.0'
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  go_router_builder: ^4.0.1
  injectable_generator: ^2.8.1

flutter:
  uses-material-design: true
